import {
  FaMobileAlt,
  FaTv,
  FaLaptop,
  FaHome,
  FaPlug,
  FaTshirt,
  FaHeart,
  FaGamepad,
  FaTools,
  FaFootballBall,
  FaBaby,
  FaThLarge,
} from "react-icons/fa";

export const categories = [
  {
    id: 1,
    name: "Phones & Tablets",
    icon: FaMobileAlt,
    imageUrl: "https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg",
    subcategories: ["Smartphones", "Tablets", "Accessories"],
    brands: ["Apple", "Samsung", "Xiaomi", "Huawei"],
  },
  {
    id: 2,
    name: "TV & High Tech",
    icon: FaTv,
    imageUrl: "https://images.pexels.com/photos/3945653/pexels-photo-3945653.jpeg",
    subcategories: ["TVs", "Projectors", "Audio"],
    brands: ["Samsung", "LG", "Sony", "TCL"],
  },
  {
    id: 3,
    name: "Computing",
    icon: FaLaptop,
    imageUrl: "https://images.pexels.com/photos/18105/pexels-photo.jpg",
    subcategories: ["PCs", "Printers", "Storage"],
    brands: ["Dell", "HP", "Asus", "Lenovo"],
  },
  {
    id: 4,
    name: "Home, Kitchen & Office",
    icon: FaHome,
    imageUrl: "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg",
    subcategories: ["Decoration", "Kitchen", "Furniture"],
    brands: ["Ikea", "Conforama", "But", "Maisons du Monde"],
  },
  {
    id: 5,
    name: "Home Appliances",
    icon: FaPlug,
    imageUrl: "https://images.pexels.com/photos/1599791/pexels-photo-1599791.jpeg",
    subcategories: ["Refrigerators", "Microwaves", "Washing Machines"],
    brands: ["Moulinex", "Bosch", "Whirlpool", "Beko"],
  },
  {
    id: 6,
    name: "Clothing & Shoes",
    icon: FaTshirt,
    imageUrl: "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    subcategories: ["Men", "Women", "Kids"],
    brands: ["Nike", "Adidas", "Zara", "H&M"],
  },
  {
    id: 7,
    name: "Beauty & Health",
    icon: FaHeart,
    imageUrl: "https://images.pexels.com/photos/3865556/pexels-photo-3865556.jpeg",
    subcategories: ["Care", "Makeup", "Health"],
    brands: ["L'Oréal", "Nivea", "Garnier", "Sephora"],
  },
  {
    id: 8,
    name: "Video Games & Consoles",
    icon: FaGamepad,
    imageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg",
    subcategories: ["PS5", "Xbox", "Nintendo"],
    brands: ["Sony", "Microsoft", "Nintendo"],
  },
  {
    id: 9,
    name: "DIY & Tools",
    icon: FaTools,
    imageUrl: "https://images.pexels.com/photos/209235/pexels-photo-209235.jpeg",
    subcategories: ["Tools", "Electricity", "Plumbing"],
    brands: ["Bosch", "Black & Decker", "Makita", "Dexter"],
  },
  {
    id: 10,
    name: "Sports & Leisure",
    icon: FaFootballBall,
    imageUrl: "https://images.pexels.com/photos/3991877/pexels-photo-3991877.jpeg",
    subcategories: ["Fitness", "Camping", "Bikes"],
    brands: ["Decathlon", "Domyos", "Adidas", "Nike"],
  },
  {
    id: 11,
    name: "Baby & Toys",
    icon: FaBaby,
    imageUrl: "https://images.pexels.com/photos/3933275/pexels-photo-3933275.jpeg",
    subcategories: ["Toys", "Strollers", "Baby Clothes"],
    brands: ["Chicco", "Fisher-Price", "Bébé Confort", "Playmobil"],
  },
  {
    id: 12,
    name: "Other Categories",
    icon: FaThLarge,
    imageUrl: "https://images.pexels.com/photos/315191/pexels-photo-315191.jpeg",
    subcategories: ["Miscellaneous", "Others"],
    brands: ["Other"],
  },
];
