export const Products = [
    {
      id: 1,
      name: "iPhone 14 Pro Max",
      category: "Téléphone & Tablette",
      imageUrl: "https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg",
      price: 1299,
      InStock: 8,
      brand: "Apple",
      rating: 4.8,
      numReviews: 154,
      description: "Smartphone haut de gamme avec écran Super Retina XDR et puce A16 Bionic.",
    },
    {
      id: 2,
      name: "TV Samsung QLED 55”",
      category: "TV & HIGH TECH",
      imageUrl: "https://images.pexels.com/photos/3945653/pexels-photo-3945653.jpeg",
      price: 849,
      InStock: 12,
      brand: "Samsung",
      rating: 4.6,
      numReviews: 78,
      description: "Téléviseur QLED avec résolution 4K et technologie HDR 10+ pour une image éclatante.",
    },
    {
      id: 3,
      name: "Ordinateur portable Dell XPS 13",
      category: "Informatique",
      imageUrl: "https://images.pexels.com/photos/18105/pexels-photo.jpg",
      price: 1099,
      InStock: 5,
      brand: "Dell",
      rating: 4.7,
      numReviews: 65,
      description: "Ultrabook léger avec écran InfinityEdge et processeur Intel Core i7.",
    },
    {
      id: 4,
      name: "Blender Moulinex Easy Mix",
      category: "Électroménager",
      imageUrl: "https://images.pexels.com/photos/1599791/pexels-photo-1599791.jpeg",
      price: 49,
      InStock: 25,
      brand: "Moulinex",
      rating: 4.4,
      numReviews: 33,
      description: "Blender compact et puissant, parfait pour les smoothies et soupes.",
    },
    {
      id: 5,
      name: "Chaussures de sport Nike Air Zoom",
      category: "Vêtements & Chaussures",
      imageUrl: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4b476e07-8dce-4d55-8ff7-49299ab0696f/NIKE+PEGASUS+PREMIUM.png",
      price: 89,
      InStock: 18,
      brand: "Nike",
      rating: 4.5,
      numReviews: 112,
      description: "Chaussures légères et confortables idéales pour le running et le sport.",
    },
    {
      id: 6,
      name: "Palette de maquillage L'Oréal",
      category: "Beauté & Santé",
      imageUrl: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-lorealparis-fr-catalog/default/dw98323331/ProductImages/OAP7043/3600523873821/3600523873821-01.jpg?sw=465&sh=465&sm=cut&sfrm=jpg&q=70",
      price: 29,
      InStock: 50,
      brand: "L'Oréal",
      rating: 4.3,
      numReviews: 47,
      description: "Palette complète avec des teintes naturelles et scintillantes pour tous les looks.",
    },
    {
      id: 7,
      name: "Console PlayStation 5",
      category: "Jeux vidéos & Consoles",
      imageUrl: "https://images.pexels.com/photos/1293269/pexels-photo-1293269.jpeg",
      price: 599,
      InStock: 10,
      brand: "Sony",
      rating: 4.9,
      numReviews: 210,
      description: "La nouvelle génération de console avec performances de jeu exceptionnelles et SSD ultra-rapide.",
    },
    {
      id: 8,
      name: "Perceuse sans fil Bosch",
      category: "Bricolage",
      imageUrl: "https://images.pexels.com/photos/209235/pexels-photo-209235.jpeg",
      price: 79,
      InStock: 22,
      brand: "Bosch",
      rating: 4.6,
      numReviews: 89,
      description: "Perceuse/visseuse puissante avec batterie longue durée et charge rapide.",
    },
    {
      id: 9,
      name: "Tapis de yoga antidérapant",
      category: "Sports & Loisirs",
      imageUrl: "https://images.pexels.com/photos/3991877/pexels-photo-3991877.jpeg",
      price: 25,
      InStock: 30,
      brand: "Decathlon",
      rating: 4.2,
      numReviews: 41,
      description: "Tapis confortable et léger pour la pratique du yoga ou du fitness.",
    },
    {
      id: 10,
      name: "Poussette bébé 3-en-1",
      category: "Bébé & Jouets",
      imageUrl: "https://images.pexels.com/photos/3933275/pexels-photo-3933275.jpeg",
      price: 199,
      InStock: 7,
      brand: "Chicco",
      rating: 4.7,
      numReviews: 36,
      description: "Poussette multifonction confortable, facile à plier et adaptée dès la naissance.",
    },
  ];
  